### ISSUE TITLE
Profiling with librato

### ISSUE THREAD

**Issue by demands** [goodeggs/librato-node#29]
Wouldn't it be cool if you could do:

```js
var profileComplete = librato.profile('third-party-service.call')
callThirdPartyService(function(err, result) {
  profileComplete();
});
```

...and have this post the timing of the call to librato?

**Comment by bobzoller** [comment]
it would.  see what you think of this:
https://github.com/goodeggs/librato-node/pull/28

**Comment by demands** [comment]
Oh hey! Nice work. :)

Just curious, in #28, is there a particular benefit of creating a new scope for the profiler?

I guess that way you can be absolutely sure that the callback gets called eventually.
The downside is now you have to stick all of your code that's being profiled into a function, which makes the profiling logic much more first-class, not just something you can sprinkle throughout your code.

What are your thoughts?

**Comment by bobzoller** [comment]
I like that my PR handles both async and sync with the same API... it also
matches Librato's client API in other languages.  And while I agree the
pattern I chose feels "more first-class", I'm expecting most folks to use
this for permanent instrumentation rather than temporary profiling.  There
could be a place for both APIs though...

```coffeescript
done = librato.timing.start 'foobar'
setTimeout done, 5000
```

```coffeescript
librato.timing 'foobar', (done) ->
  setTimeout done, 5000
```

or even

```coffeescript
done = librato.timing 'foobar' # no function param so return the done fn
setTimeout done, 5000
```

**Comment by demands** [comment]
Oo fancy times. I love it. :sunglasses:
